{
 "title": "Akka Actor System",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Job",
    "label": "Job",
    "query": "label_values(akka_system_processed_messages_total, job)"
   },
   {
    "name": "actorsystem",
    "label": "Actor System",
    "query": "label_values(akka_system_processed_messages_total{job=~\"$Job\"}, system)"
   },
   {
    "name": "dispatcher",
    "label": "dispatcher",
    "query": "label_values(executor_threads_sum{actor_system=~\"$actorsystem\", state!=\"active\", job=~\"$Job\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Actor System Processed messages",
   "type": "graph",
   "description": "Processed messages by actor system",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rate / [s]" }
   ],
   "targets": [
    {
     "expr": "sum by(job, system)(rate(akka_system_dead_letters_total{system=~\"$actorsystem\", job=~\"$Job\"}[2m]))",
     "legendFormat": "dead letters"
    },
    {
     "expr": "sum by(job, system) (rate(akka_system_unhandled_messages_total{system=~\"$actorsystem\", job=~\"$Job\"}[2m]))",
     "legendFormat": "unhandled_messages"
    },
    {
     "expr": "sum by(job, system) (rate(akka_system_processed_messages_total{system=~\"$actorsystem\", tracked=\"false\", job=~\"$Job\"}[2m]))",
     "legendFormat": "processed messages"
    }
   ]
  },
  {
   "title": "Dead Letters queue",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (job, system)(akka_system_dead_letters_total{ system=~\"$actorsystem\", job=~\"$Job\"})"
    }
   ]
  },
  {
   "title": "Unhanded messages",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (job, system)(akka_system_unhandled_messages_total{system=~\"$actorsystem\", job=~\"$Job\"})"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 } },
  {
   "title": "Avg Active Actors",
   "type": "graph",
   "description": "Average count of actors in the system",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_system_active_actors_sum{system=~\"$actorsystem\", job=~\"$Job\"}/akka_system_active_actors_count{system=~\"$actorsystem\", job=~\"$Job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Akka dispatcher - $dispatcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "dispatcher" },
  {
   "title": "Threads count",
   "type": "graph",
   "description": "A number of threads used",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(executor_pool{actor_system=~\"$actorsystem\", setting=\"max\", name=~\"$dispatcher\", job=~\"$Job\"})",
     "legendFormat": "MAX "
    },
    {
     "expr": "executor_threads_sum{actor_system=~\"$actorsystem\", name=~\"$dispatcher\", state=\"active\", job=~\"$Job\"}/executor_threads_count{actor_system=~\"$actorsystem\", name=~\"$dispatcher\", state=\"active\", job=~\"$Job\"}",
     "legendFormat": "ACTIVE {{instance}}"
    }
   ]
  },
  {
   "title": "Executor Queue size histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(le)(increase(executor_queue_bucket{ actor_system=~\"$actorsystem\", name=~\"$dispatcher\", job=~\"$Job\"}[2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Executor tasks",
   "type": "graph",
   "description": "Tracks the number of tasks processed by the executor service",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_tasks_total{actor_system=\"$actorsystem\",name=~\"$dispatcher\", state!=\"submitted\", job=~\"$Job\"}",
     "legendFormat": "{{state}} / {{instance}}"
    }
   ]
  }
 ]
}