{
 "title": "JVM metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(jvm_memory_buffer_pool_count, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Class loaded",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_class_loading{instance =~\"$node\"}",
     "legendFormat": "{{instance}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Number of threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads{ instance =~\"$node\"}",
     "legendFormat": "{{instance}} - {{measure}}"
    }
   ]
  },
  {
   "title": "heap size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(rate(jvm_memory_bytes_sum{ segment=\"heap\", instance =~\"$node\"}[5m])/rate(jvm_memory_bytes_count{ segment=\"heap\", instance =~\"$node\"}[5m]))",
     "legendFormat": "{{instance}} - {{segment}}-{{measure}}"
    }
   ]
  },
  {
   "title": "non-heap memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(rate(jvm_memory_bytes_sum{ segment=\"non-heap\", instance =~\"$node\"}[5m])/rate(jvm_memory_bytes_count{ segment=\"non-heap\", instance =~\"$node\"}[5m]))",
     "legendFormat": "{{instance}}-{{measure}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_seconds_sum{ instance=~\"$node\"}[2m])/rate(jvm_gc_seconds_count{ instance =~\"$node\"}[2m])",
     "legendFormat": " {{instance}}  GC count: {{collector}}"
    }
   ]
  }
 ]
}